# Generated by Django 6.0.5 on 2026-06-06 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('price', models.PositiveIntegerField(default=0)),
                ('old_price', models.PositiveIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='app.product')),
            ],
            options={
                'db_table': 'product_variants',
                'unique_together': {('product', 'name')},
            },
        ),
    ]
