# Generated by Django 6.0.7 on 2026-08-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_completedorder_tariff_delete_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namber', models.CharField(max_length=150, verbose_name='Номер')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
                ('adress_from', models.TextField(blank=True, verbose_name='Звідки')),
                ('adress_to', models.TextField(blank=True, verbose_name='Куди')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Виділити')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'db_table': 'orders',
                'ordering': ('order', 'pk'),
            },
        ),
    ]
