# Generated by Django 6.0.7 on 2026-08-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Бажана дата'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Орієнтовний час'),
        ),
    ]
